apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: akimabs-example-k8s
spec:
  selector:
    matchLabels:
      app: akimabs-example-k8s
  template:
    metadata:
      labels:
        app: akimabs-example-k8s
    spec:
      containers:
        - name: akimabs-example-k8s
          image: akimabs/example:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
