apiVersion: apps/v1
kind: Deployment
metadata:
  name: akimabs-example-k8s
spec:
  selector:
    matchLabels:
      app: akimabs-example-k8s
  template:
    metadata:
      labels:
        app: akimabs-example-k8s
    spec:
      containers:
        - name: akimabs-example-k8s
          image: akimabs/image-spring:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: akimabs-example-k8s-svc
spec:
  selector:
    app: akimabs-example-k8s
  ports:
    - protocol: "TCP"
      port: 8080
  type: NodePort
